# Enable/Disable Built-In Features
aha_board: true
question_board: false
gallery: false

# Custom Sidebar Links to External Sites.
# ----------------------------------------
# Must be an array.  Start with a dash on its own line.
# Then indent and provide label, url, and fa icon (optional)
# The default icon is fa-cloud.
sidebar:

  # -
  #   label: "Canvas Discussion"
  #   url: "https://canvas.northwestern.edu/courses/9507/discussion_topics"
  #   icon: fa-question-circle

